AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseName:
    Type: String
    Default: Sample_Database

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DatabaseName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-AuthorizerFunction
      CodeUri: dist/authorizer
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Tracing: Active

  # Allow any API in the account to invoke the lambda authorizer function
  InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref AuthorizerFunction
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/authorizers/*

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - '*'
        AllowMethods:
          - GET
          - OPTIONS
        AllowOrigins:
          - http://*
          - https://*
      Auth:
        Authorizers:
          # https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html
          LambdaAuthorizer:
            FunctionPayloadType: REQUEST
            AuthorizerPayloadFormatVersion: '2.0'
            EnableSimpleResponses: False
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0
        DefaultAuthorizer: LambdaAuthorizer

  GetAllData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-GetAllDataFunction
      CodeUri: dist/dynamoController
      Handler: index.getAllItemsHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DatabaseName
      Environment:
        Variables:
          DB_TABLE_NAME: !Ref DatabaseName
      Events:
        HttpApiGET:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'

Outputs:
  HttpApiURL:
    Description: 'HTTP API URL'
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
