AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - '*'
        AllowMethods:
          - GET
          - OPTIONS
        AllowOrigins:
          - http://*
          - https://*

  GetData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-GetData
      CodeUri: dist
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Events:
        HttpApiGET:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'
    Metadata:
      RuntimeOption: typescript

Outputs:
  RestApiURL:
    Description: 'HTTP API URL'
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
